thomas-mauran/LinkedOut

docs/openapi/api_gateway.yml
mock/db.json
mock/routes.json

- use uuid instead of incrementals ids

chore: use uuid instead of incrementals ids

---

docs/openapi/api_gateway.yml
mock/db.json

- add job and company in jobOffer

feat: jobOffers add job and comapny + db add fields

---

docker-compose.yml

This cleans up the root `docker-compose.yml` file a bit to fix the versions for the different services, setting explicitly Postgres credentials and adding a comment to separate the different services (for now, we only bring up Keycloak but this is expected to change in the future with the arrival of NATS).
In the future, we shall share the Postgres database for all services that requires it by creating the necessary databases and users with an init script.

refactor: clean up the docker compose file

---

front/assets/translations/en_US.json
front/assets/translations/fr_FR.json
front/package-lock.json
front/package.json
front/src/components/jobOffers/JobOfferItem.tsx
front/src/components/jobOffers/JobOfferList.tsx
front/src/models/entities/jobOffer.ts
front/src/pages/internal/InternalPagesNav.tsx
front/src/pages/internal/InternalPagesPage.tsx
front/src/pages/jobOffer/JobOfferNav.tsx
front/src/pages/jobOffer/JobOfferPage.tsx
front/src/store/api/apiSlice.ts
front/src/store/api/jobApiSlice.ts

feat(JobOffer): Job offet list

---

front/assets/translations/en_US.json
front/assets/translations/fr_FR.json
front/src/components/jobOffers/JobOfferContent.tsx
front/src/components/jobOffers/JobOfferItem.tsx
front/src/components/jobOffers/JobOfferList.tsx
front/src/pages/jobOffer/JobOfferListPage.tsx
front/src/pages/jobOffer/JobOfferNav.tsx
front/src/pages/jobOffer/JobOfferPage.tsx
front/src/store/api/jobApiSlice.ts
front/src/store/api/jobOfferApiSlice.ts

- Job offer press and view
- apply to job offer

feat(jobOffer): job offer view and apply

---

.github/workflows/on_push_pr_main.yml

This updates the CI to detect directories that changed and run the appropriate jobs (e.g., if you update the frontend, only the CI jobs pertaining to the frontend will run).
This also adds a concurrency group to avoid running the pipeline if a newer ref is available.
Those changes only applies to the "Push & PR" pipeline. The "Semver tag" pipeline remains unchanged.

ci: add conditional execution and concurrency group

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/MessagingController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/model/Employer.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/model/MessageChannel.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/JobCategoryService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/JobService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/MessageChannelsService.kt
backend/api_gateway/src/main/resources/application.yml
backend/jobs/src/main/kotlin/com/linkedout/jobs/function/jobs/GetJob.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/MessagingApplication.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messageChannels/GetChannelOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messageChannels/GetChannelsOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messaging/FindAllUserMessageChannels.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messaging/FindOneUserMessageChannel.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/model/MessageChannel.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/repository/MessageChannelRepository.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/service/MessageChannelService.kt
backend/messaging/src/main/resources/application.properties
backend/messaging/src/main/resources/db/migration/V1__initial_state.sql
backend/protobuf/src/main/proto/models/messageChannel.proto
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/messaging.proto

This implements the methods in the messaging service to get a single message channel and all message channels of a user through the message broker.
The corresponding API gateway routes were also implemented for the currently logged-in user.
Explicit calls to some getters were removed.

feat(messaging): implement findOneUserMessageChannel and findAllUserMessageChannels

---

.github/workflows/on_push_pr_main.yml
.github/workflows/on_semver_tag.yml
backend/employer/build.gradle.kts
backend/employer/src/main/kotlin/com/linkedout/employer/EmployerApplication.kt
backend/employer/src/main/kotlin/com/linkedout/employer/function/employer/GetEmployer.kt
backend/employer/src/main/kotlin/com/linkedout/employer/model/Employer.kt
backend/employer/src/main/kotlin/com/linkedout/employer/repository/EmployerRepository.kt
backend/employer/src/main/kotlin/com/linkedout/employer/service/EmployerService.kt
backend/employer/src/main/resources/application.properties
backend/employer/src/main/resources/application.yml
backend/employer/src/main/resources/db/migration/V1__initial_state.sql
backend/employer/src/test/kotlin/com/linkedout/employer/EmployerApplicationTests.kt
backend/protobuf/src/main/proto/models/employer.proto
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/employer.proto
backend/settings.gradle.kts
config/postgres/init.sql

This adds the skeleton of the `employer` service in the backend. The method to get a single employer through the message broker was also implemented.

feat(backend): bootstrap employer service and implement findOne

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/JobCategoriesController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/JobsController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/MessagingController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/EmployerService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/JobCategoryService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/JobService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/MessageChannelsService.kt
backend/api_gateway/src/main/resources/application.yml
backend/employer/src/main/kotlin/com/linkedout/employer/function/employer/GetMultipleEmployers.kt
backend/employer/src/main/kotlin/com/linkedout/employer/service/EmployerService.kt
backend/employer/src/main/resources/application.properties
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/employer.proto

This adds data about the employer on the `/messaging` and `/messaging/{channelId}` route responses by using the new `employer` service.
In the API gateway, reactive types were moved out of the services and now handled exclusively in the controllers.

feat(api_gateway): add employer data in message channels

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/MessagingController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/model/Message.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/MessageChannelService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/MessageService.kt
backend/api_gateway/src/main/resources/application.yml
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messageChannels/GetChannelOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messages/GetMessagesOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/model/Message.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/repository/MessageRepository.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/service/MessageService.kt
backend/messaging/src/main/resources/application.properties
backend/messaging/src/main/resources/db/migration/V1__initial_state.sql
backend/messaging/src/main/resources/db/migration/V2__add_message_table.sql
backend/protobuf/src/main/proto/models/employer.proto
backend/protobuf/src/main/proto/models/message.proto
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/messaging.proto

This implements the method in the messaging service to get the messages in a message channel of a user through the message broker.
The corresponding API gateway route was also implemented for the currently logged-in user.
In the API gateway, the `MessageChannelsService` class was renamed to `MessageChannelService`.
In the protobuf files, snake case is enforced on message properties. The `get_user_message_channel_by_id_*` items were renamed to `get_user_message_channel_*`.

feat(messaging): implement getMessagesOfUser

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/EmployerController.kt

This adds a route in the API gateway to get an employer by its ID.

feat(api_gateway): add route to get an employer

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/EmployerController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/MessagingController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/dto/messaging/SendMessageDto.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/MessageChannelService.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/MessageService.kt
backend/api_gateway/src/main/resources/application.yml
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messageChannels/GetChannelOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messageChannels/GetChannelOfUserWithEmployer.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messageChannels/GetChannelsOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messages/GetMessagesOfUser.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messages/SendMessage.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/function/messages/SendMessageToEmployer.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/model/Message.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/model/MessageChannelWithLastMessage.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/repository/MessageChannelRepository.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/repository/MessageRepository.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/service/MessageChannelService.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/service/MessageService.kt
backend/messaging/src/main/kotlin/com/linkedout/messaging/utils/MessageDirection.kt
backend/messaging/src/main/resources/application.properties
backend/messaging/src/main/resources/db/migration/V1__initial_state.sql
backend/messaging/src/main/resources/db/migration/V3__unique_seasonworker_employer_couple_on_channels.sql
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/messaging.proto

The following methods were implemented to be used through the message broker:
- `sendMessage` : sends a message to the specified message channel, corresponds to the `POST /messaging/{messageChannelId}/messages` API route
- `findOneChannelOfUserWithEmployer` : gets the messaging channel between a seasonworker and an employer, corresponds to the `GET /employers/{employerId}/messaging` API route
- `sendMessageToEmployer` : sends a message to the specified employer, corresponds to the `POST /employers/{employerId}/messaging` API route
An enum has been created to list the possible message directions.
A constraint has been added to the `MessageChannel` table to ensure that a single `(seasonworkerId, employerId)` couple exists.
The last message of a channel is now sent when requesting message …

feat(messaging): finish implementation

---

front/src/components/notifications/NotificationItem.tsx
front/src/components/notifications/NotificationList.tsx
front/src/models/entities/notification.ts
front/src/pages/messaging/MessageTabBarNav.tsx
front/src/pages/messaging/MessagingNav.tsx
front/src/pages/notifications/NotificationlListPage.tsx
front/src/store/api/apiSlice.ts
front/src/store/api/notificationApiSlice.ts
mock/config/db.json

- notification list 
- message and notification in tabs

feat: notification tab

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/ProfileController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/ProfileService.kt
backend/api_gateway/src/main/resources/application.yml
backend/common/src/main/kotlin/com/linkedout/common/utils/CloudStreamErrorHandler.kt
backend/common/src/main/kotlin/com/linkedout/common/utils/RequestResponseFactory.kt
backend/profile/build.gradle.kts
backend/profile/src/main/kotlin/com/linkedout/profile/config/S3ClientConfiguration.kt
backend/profile/src/main/kotlin/com/linkedout/profile/config/S3ClientConfigurationProperties.kt
backend/profile/src/main/kotlin/com/linkedout/profile/function/attachment/GetCvOfUser.kt
backend/profile/src/main/kotlin/com/linkedout/profile/function/attachment/GetProfilePictureOfUser.kt
backend/profile/src/main/kotlin/com/linkedout/profile/function/attachment/SetCvOfUser.kt
backend/profile/src/main/kotlin/com/linkedout/profile/function/attachment/SetProfilePictureOfUser.kt
backend/profile/src/main/kotlin/com/linkedout/profile/service/AttachmentService.kt
backend/profile/src/main/resources/application.properties
backend/profile/src/main/resources/application.yml
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/profile.proto

This implements the functions in the `profile` service to store attachments (profile picture, CV) to a profile. The following methods were implemented to be used through the message broker:
- `findOneCvOfUser` : gets the CV of a user, corresponds to the `GET /profile/cv` API route
- `saveOneCvOfUser` : sets the CV of a user, corresponds to the `POST /profile/cv` API route
- `findOneProfilePictureOfUser` : gets the profile picture of a user, corresponds to the `GET /profile/photo` API route
- `saveOneProfilePictureOfUser` : sets the profile picture of a user, corresponds to the `POST /profile/photo` API route
The attachments are stored in an S3-compatible object storage that can be configured in the `profile` service configuration.

feat(profile): implement profile picture and cv routes

---

backend/Dockerfile

This fixes the backend container images by correcting the JAR file name that is copied into the last stage.

fix(docker): copy the correct jar file

---

backend/profile/src/main/kotlin/com/linkedout/profile/repository/ProfileRepository.kt

This sets a default value for the average rating returned by the `GET /profile` route if the user has no evaluation yet.

fix(profile): set default value for the average rating

---

front/assets/translations/en_US.json
front/assets/translations/fr_FR.json
front/src/pages/LoggedInNav.tsx
front/src/pages/MainTabNav.tsx
front/src/pages/jobOffer/JobOfferNav.tsx
front/src/pages/profile/ProfileNav.tsx

This adds a bottom navigation bar navigator for the user to navigate through the app when they are logged in and have a profile created.

feat(front): add main navigator

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/controller/JobOffersController.kt
backend/api_gateway/src/main/kotlin/com/linkedout/backend/service/JobOfferService.kt
backend/api_gateway/src/main/resources/application.yml
backend/jobs/src/main/kotlin/com/linkedout/jobs/function/jobOffers/GetJobOffersAppliedForUser.kt
backend/jobs/src/main/kotlin/com/linkedout/jobs/repository/JobOfferRepository.kt
backend/jobs/src/main/kotlin/com/linkedout/jobs/service/JobOfferService.kt
backend/jobs/src/main/resources/application.properties
backend/profile/src/main/kotlin/com/linkedout/profile/function/profile/SetProfileOfUser.kt
backend/protobuf/src/main/proto/request.proto
backend/protobuf/src/main/proto/response.proto
backend/protobuf/src/main/proto/services/jobs.proto
front/assets/translations/en_US.json
front/assets/translations/fr_FR.json
front/src/pages/MainTabNav.tsx
front/src/pages/jobOffer/JobOfferApplicationNav.tsx
front/src/pages/jobOffer/JobOfferNav.tsx
front/src/pages/jobOffer/jobOfferApplicationPage.tsx
front/src/pages/login/FirstLoginPage.tsx
front/src/store/api/jobOfferApiSlice.ts

This pr add the jobOfferApplication route in the back when we GET on this route on the jobOffers route with the onlyApplied=true. We also show the applied job offers in the front page.

feat: job offer application

---

front/assets/translations/en_US.json
front/assets/translations/fr_FR.json
front/src/components/employer/EmployerEvaluationContent.tsx
front/src/components/employer/EmployerEvaluationForm.tsx
front/src/components/jobOffers/JobOfferContent.tsx
front/src/components/jobOffers/JobOfferMessageSender.tsx
front/src/components/messaging/MessageChannelContent.tsx
front/src/components/messaging/MessageChannelList.tsx
front/src/components/messaging/MessageTextInput.tsx
front/src/models/dtos/employer/createEmployerEvaluationDto.ts
front/src/models/dtos/employer/createEmployerMessageDto.ts
front/src/models/entities/jobOffer.ts
front/src/pages/employer/EmployerEvaluationPage.tsx
front/src/pages/jobOffer/JobOfferNav.tsx
front/src/pages/jobOffer/JobOfferPage.tsx
front/src/pages/login/FirstLoginPage.tsx
front/src/pages/messaging/MessageChannelPage.tsx
front/src/pages/messaging/MessagingNav.tsx
front/src/store/api/apiSlice.ts
front/src/store/api/employerApiSlice.ts

This adds a form to send a message to the employer that created a job offer whose the season worker has been accepted.
This also reworks the employer evaluation screen to fetch the current evaluation instead of having a default form, add a button to delete the evaluation, and make this view available in the message view and job offer view when the offer has been accepted.

feat(front): improve employer messaging and evaluation

---

backend/api_gateway/src/main/kotlin/com/linkedout/backend/config/WebFluxConfiguration.kt
backend/api_gateway/src/main/resources/application.yml
front/app.json
front/assets/translations/en_US.json
front/assets/translations/fr_FR.json
front/package-lock.json
front/package.json
front/src/components/profile/ProfileShareResumeButton.tsx
front/src/components/profile/ProfileUpdateInfosForm.tsx
front/src/components/profile/ProfileUploadPictureButton.tsx
front/src/components/profile/ProfileUploadResumeButton.tsx
front/src/components/profile/header/ProfileHeader.tsx
front/src/global.d.ts
front/src/pages/profile/ProfilePage.tsx
front/src/pages/profile/ProfileUpdatePage.tsx
front/src/store/api/apiSlice.ts
front/src/store/api/profileApiSlice.ts
kube/prod/api_gateway/configure-ingress.patch.yml

This adds the logic to upload the profile picture and resume, to get the user profile picture and to share the user resume PDF file.
The Spring codec max in-memory size limit has been increased to 8 MB.

feat(front): add file upload and fetch

---

.github/workflows/flow_backend_build_push.yml
.github/workflows/on_push_pr_main.yml
.github/workflows/on_semver_tag.yml
backend/Dockerfile
kube/base/api_gateway/deployment.yml
kube/base/employer/deployment.yml
kube/base/jobs/deployment.yml
kube/base/messaging/deployment.yml
kube/base/notification/deployment.yml
kube/base/profile/deployment.yml
kube/base/recommendation/deployment.yml
kube/prod/add-resource-limits.patch.yml
kube/prod/kustomization.yml
kube/prod/kyverno-policy.yml
kube/prod/network-policies.yml

This improves the overall security of the project by doing the following:
- Sign the container images that are pushed to GHCR via the CI
- Add an image signature verification policy in Kubernetes
- Run the microservices as a non-root user in the containers
- Drop privileges in the Kubernetes deployments
- Configure resource limits for the containers in Kubernetes
- Configure network policies in Kubernetes
The `dorny/paths-filter` action in the CI has been updated to `v3`.

feat: improve infrastructure security
